# Generated by Django 4.1.3 on 2022-12-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Department',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='salary',
        ),
    ]
