# Generated by Django 4.1.3 on 2022-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_department_doctor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_surname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
