# Generated by Django 4.1.3 on 2022-12-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_doctor_user_name_doctor_user_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='user_surname',
            new_name='doctor_surname',
        ),
    ]
