# Generated by Django 4.1.3 on 2022-12-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_name_doctor_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_email',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='inspection_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='inspection_phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
