# Generated by Django 4.1.3 on 2022-12-29 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_remove_doctor_age_remove_doctor_phone_doctor_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('surname', models.CharField(max_length=25, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('inspection_address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('department', models.CharField(max_length=20, verbose_name='Department')),
                ('degree', models.CharField(max_length=20, verbose_name='Degree')),
                ('status', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
