# Generated by Django 4.1.3 on 2022-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_doctorlogin_registerdoctor_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdoctor',
            name='username',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='registerdoctor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
