# Generated by Django 4.1.3 on 2023-01-12 11:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_registerdoctor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdoctor',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
