# Generated by Django 4.1.3 on 2023-01-12 18:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_registerdoctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlogin',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='doctorlogin',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='registerdoctor',
            name='degree',
            field=models.CharField(choices=[('Pratisyen Dr.', 'Pratisyen Dr.'), ('Dr.', 'Dr.'), ('Uzm. Dr.', 'Uzm. Dr.'), ('Doc. Dr.', 'Doc. Dr.'), ('Op. Dr.', 'Op. Dr.'), ('Doc. Dr.', 'Doc. Dr.'), ('Prof. Dr.', 'Prof. Dr.')], max_length=20, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='registerdoctor',
            name='department',
            field=models.CharField(choices=[('Dermatoloji', 'Dermatoloji'), ('İç Hastalıkları', 'İç Hastalıkları'), ('Beyin ve Sinir Cerrahisi', 'Beyin ve Sinir Cerrahisi'), ('Ortopedi ve Travmatoloji', 'Ortopedi ve Travmatoloji'), ('Kulak Burun Boğaz (KBB)', 'Kulak Burun Boğaz (KBB)'), ('Onkoloji', 'Onkoloji'), ('Çocuk Hastalığı ve Hastalıkları', 'Çocuk Hastalığı ve Hastalıkları'), ('Göğüs Hastalıkları', 'Göğüs Hastalıkları'), ('Üroloji', 'Üroloji'), ('Psikiyatri', 'Psikiyatri'), ('Kadın Hastalıkları ve Doğum', 'Kadın Hastalıkları ve Doğum'), ('Göz Hastalıkları', 'Göz Hastalıkları'), ('Fiziksel Tıp ve Rehabilitasyon', 'Fiziksel Tıp ve Rehabilitasyon'), ('Diş Hekimliği', 'Diş Hekimliği'), ('Enfeksiyon Hastalıkları', 'Enfeksiyon Hastalıkları'), ('Beslenme ve Diyetetik Diyetisyen', 'Beslenme ve Diyetetik Diyetisyen'), ('Kardiyoloji', 'Kardiyoloji')], max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='registerdoctor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, region='TR'),
        ),
    ]
